
# PLEASE ADJUST THE FOLLOWING PARAMETERS --------------------------------------

hic_file_ending: .txt
gene_data_file_ending: .txt
delta: [50, 100]
go_reference_species: human
go_sample_pool_size: 10000000
go_sample_max_cluster_size: 25

#------------------------------------------------------------------------------


# DO NOT ADJUST THE FOLLOWING PARAMETERS (unless you know what you are doing) -

bin_dir: scripts
hic_data_dir: data/hic_maps
truncated_data_dir: truncated
normalized_data_dir: normalized_hic_maps
graph_data_dir: graphs
gene_data_dir: data/genomic
graph_teams_dir: teams
go_analysis_dir: go_analysis
go_data_dir: data/go


