
# PLEASE ADJUST THE FOLLOWING PARAMETERS --------------------------------------

hic_file_ending: .trv
hic_map_format: HOMER # choices are DIXON, HOMER
# set hic row/column offset explicitely
# hic_row_offset: 0
# hic_col_offset: 0
#
gene_data_file_ending: .gff
gene_data_format: GFF3 # choices are ENSEMBLE, GFF3
delta: #[-2.25, -2.5, -2.75] #[-1.75, -1.5, -1.25, -1, -0.75, -0.5, -0.25, 0]
delta: [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]
max_delta: 5
go_reference_species: AL
normalization_type: AVG # choices are AVG, MAX
go_sample_pool_size: 10000000
go_sample_max_cluster_size: 25
#compare_only: [AR, BR]

# make sure no genome name contains delimiters '-' or '_'
diff_pairs: [[AR, AL], [BR, BL]] #[[AL, AR], [BL, BR]] #

#------------------------------------------------------------------------------


# DO NOT ADJUST THE FOLLOWING PARAMETERS (unless you know what you are doing) -

bin_dir: scripts
hic_data_dir: data/hic_maps
normalized_data_dir: normalized_hic_maps
graph_data_dir: graphs
gene_data_dir: data/genomic
graph_teams_dir: teams
go_analysis_dir: go_analysis
go_data_dir: data/go
log_dir: logs
